### ISSUE TITLE
Reference_scenario_curtailment crashes for certain time frames

### ISSUE THREAD

**Issue by pamelagp** [windnode/WindNODE_KWUM#19]
https://github.com/windnode/WindNODE_KWUM/blob/89c0a6ac41a9224b10ac62c7c7764f27d7a7a24e/windnode_kwum/scenarios/reference_scenario_curtailment.py#L111

Hello, I have been testing the following small timeframes on reference_scenario_curtailment.py:

- date_from: 2016-02-01 00:00:00
- date_to: 2016-02-01 09:00:00
and
- date_from: 2016-02-01 00:00:00
- date_to: 2016-02-01 10:00:00

The app crashes for the line referenced in this issue (L111). You'll find attached a screenshot with the error traceback. It seems to have a problem with the calculation for 'tick_distance' and the 'range()' method can't accept a value of '0'.

![whatsapp image 2018-10-17 at 11 00 42 am](https://user-images.githubusercontent.com/35731205/47075703-58b52e00-d1fd-11e8-91b1-78f673a1dee6.jpeg)

**Comment by nesnoj** [comment]
Outdated
