### ISSUE TITLE
1st version of basic model

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_KWUM#2]
I finished a first version of our model. Some relevant notes for you:

**Basic model**
This [basic model](https://github.com/windnode/WindNODE_KWUM/blob/b2ba340cda2400d79e073a5faced469ee047ad37/windnode_kwum/model/KWUM_basic.py) is rather a scenario reader than a model, since the scenario is defined using an Excel file (see below).

**Example scenarios**
I created a basic example scenario which consists of:
- The [main file](https://github.com/windnode/WindNODE_KWUM/blob/b2ba340cda2400d79e073a5faced469ee047ad37/windnode_kwum/scenarios/basic_scenario.py) to be executed. It contains some basic config stuff in the main function since I tried to avoid keeping track of another config file...
- An [Excel file](https://github.com/windnode/WindNODE_KWUM/blob/b2ba340cda2400d79e073a5faced469ee047ad37/windnode_kwum/scenarios/data/basic_scenario.xlsx) in the subfolder `data/` which is used to configure the scenario (a basic description is included). It defines the components we agreed on last week. I used a CHP (BHKW) as thermal plant.
- Additionally, I added an [extended scenario](https://github.com/windnode/WindNODE_KWUM/blob/b2ba340cda2400d79e073a5faced469ee047ad37/windnode_kwum/scenarios/data/extended_scenario.xlsx) with some more components which we are going to investigate (e.g. 2 buses and P2H plants for heat in Nechlin and Prenzlau). To achieve a system with all components there's some work to be done..

For now, I used subfolder `data/` to store the scenario Excel files. To meet future disclosure requirements, we have to either move it to our parent data dir (which is created automatically) later, or we only move the the confidential stuff there.

I added some basic plots for testing purposes which must be improved - feel free!
I like the [graph plot](https://github.com/windnode/WindNODE_KWUM/blob/3584ec248c2d431884365d7f9076cfbc57023c30/windnode_kwum/scenarios/basic_scenario.py#L45-L46) which gives a quick overview of the created system. You may run into errors with this plot since it needs additional packages (networkx and pygraphviz).

Note: I dropped the CSV-reader (mentioned in my last mail) since it is quite a pain to configure and the function is deprecated in oemof (will be removed in the v0.2.0 release). :man_facepalming:

**New oemof**
The new oemof release v0.2.0 is just around the corner with some major (API) changes. Therefore, I did all implementations according the current state in the [developer branch](https://github.com/oemof/oemof/tree/dev). If you intend to run our model prior to this release, you have to clone and manually install it:
```
pip3 uninstall oemof
git clone https://github.com/oemof/oemof.git   (executed in your repo dir, e.g. C:\repos\)
pip3 install - <PATH_TO_OEMOF_REPO>   (in this example C:\repos\oemof)
```

**Tasks**
- Please have a look at the current state, I'd appreciate some feedback on the following questions:
  - Is the implementation appropriate from you point of view?
  - Does the basic scenario reflect what we agreed on? (except the assumptions such as capacity, efficiency etc. I used)
  - How can we handle the conflict between 1) having scenario data in the repo (which makes it a lot easier for us to share) and 2) future nondisclosure requirements?
  - more comments?
- @elisagaudchau: I'd appreciate if you modify the basic scenario - replace my assumptions and estimations by realistic numbers (some sources below). In the scenario sheets I already added some real numbers (see comments in the sheet).

I propose to talk about it next week in our webco (December 6th).

**Sources**
I did some short literature review on the region's energy system, that's what I stumbled upon:
[1] http://www.prenzlau.eu/sixcms/media.php/569/Fernw%C3%A4rmekonzept_Innenstadt.pdf
[2] http://www.nechlin.de/energiespeicher/geschichte/
[3] [Power plants from OEDB](http://oep.iks.cs.ovgu.de/dataedit/view/supply) to model more components

**Comment by nesnoj** [comment]
A major change in oemof was implemented: From now, nodes are not auto-registrated and have to be added explicitly to the energy system ([PR](https://github.com/oemof/oemof/pull/374) in oemof). I adapted our model accordingly in 7b0905b31de3828a79f1da8600d7024abcacd23f .

**Comment by elisagaudchau** [comment]
my experience with installing pygraphviz under windows:

- it doesnt work with pip install
- i downloaded the whl-file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pygraphviz and installed this with pip install "name_of_whl_file.whl"
- thats not enough, you also have to install graphviz, i followed this instructions: https://stackoverflow.com/a/36442170 (windows installer and system variable path...)

**Comment by nesnoj** [comment]
On Ubuntu(+derivatives), it's kind of painful too, see ([1](https://stackoverflow.com/questions/40528048/pip-install-pygraphviz-no-package-libcgraph-found), [2](https://github.com/pygraphviz/pygraphviz/issues/71#issuecomment-138999823)) for help.

**Comment by elisagaudchau** [comment]
I made some adaptions in the basic model (commit 4c254f8):

- Wind and PV timeseries are now more realistic
- "active" is now available for all components
- variable costs can now also be set for excess and in/output of storage
- variable costs of transformer now refer to the INput flow (in order to model taxes for P2H)
- fixed costs doesnt exist anymore
- transformer output has no min and max anymore
- one can define a timeseries for the transformer input maximum (in order to make shure that only curtailment anergy is used in P2H / P2G; attention: therefore the nominal value of the input ("max nom input") has to be the maximum power which can be fed into the grid normally.
