### ISSUE TITLE
fix auto-creation of data dir (windows)

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_KWUM#3]
@elisagaudchau You mentioned the data dir ("WindNODE_KWUM_data") is not created automatically on windows. Could you please provide the full stacktrace? (error messages)

**Comment by elisagaudchau** [comment]
ok, i´m confused. i deleted the folder and tried it again... and it works! 
with this message:
> WARNING:windnode_kwum:WindNODE_KWUM
>  data root path C:\Repos\windnode\WindNODE_KWUM\windnode_kwum\../..\WindNODE_KWUM_data 
> not found, I will create it including subdirectories.

i am absolutely shure, yesterday i had to create the directories manually...

**Comment by kasparknorr** [comment]
Hi

**Comment by nesnoj** [comment]
Welcome @kasparknorr
