### ISSUE TITLE
test with oemof v0.2.0

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_KWUM#4]
As [oemof v0.2.0](https://github.com/oemof/oemof/releases/tag/v0.2.0) was released recently, our model needs to be tested with this version.

**Comment by nesnoj** [comment]
Adapted and tested

**Comment by kasparknorr** [comment]
When I try to run 
WindNODE_KWUM\windnode_kwum\scenarios\basic_scenario.py
I get the error message:
    from oemof.outputlib import processing, views
ImportError: cannot import name 'processing'

**Comment by nesnoj** [comment]
Which oemof version r u running?
Did you install oemof using normal `pip3 install oemof` or manually from cloned repo using `pip3 install -e <PATH_TO_CLONED_REPO>`?
